import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { AssetSummary } from "@shared/schema";

interface CombinedReportProps {
  assets: AssetSummary[];
  totalValue: string;
}

export default function CombinedReport({
  assets,
  totalValue,
}: CombinedReportProps) {
  const handleDownloadPDF = () => {
    try {
      // For now, we'll create a simple HTML report that can be printed as PDF
      const reportWindow = window.open("", "_blank");
      if (!reportWindow) {
        alert("Please allow popups for this site to download the PDF report.");
        return;
      }

      const reportHTML = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>AssetLens - Combined Asset Report</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
            .header { text-align: center; margin-bottom: 40px; border-bottom: 2px solid #e5e7eb; padding-bottom: 20px; }
            .summary { background: #f9fafb; padding: 20px; border-radius: 8px; margin-bottom: 30px; }
            .asset { margin-bottom: 30px; border: 1px solid #e5e7eb; border-radius: 8px; padding: 20px; }
            .asset-header { display: flex; justify-content: between; align-items: center; margin-bottom: 15px; }
            .asset-type { background: #3b82f6; color: white; padding: 4px 12px; border-radius: 20px; font-size: 12px; }
            .asset-type.property { background: #10b981; }
            .value { font-size: 24px; font-weight: bold; color: #3b82f6; }
            .details { margin-top: 15px; }
            .detail-row { display: flex; justify-content: space-between; padding: 5px 0; border-bottom: 1px solid #f3f4f6; }
            .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #6b7280; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>AssetLens - Combined Asset Report</h1>
            <p>Generated on ${new Date().toLocaleDateString("en-US", {
              year: "numeric",
              month: "long",
              day: "numeric",
            })}</p>
          </div>

          <div class="summary">
            <h2>Portfolio Summary</h2>
            <div class="detail-row">
              <span>Total Portfolio Value:</span>
              <span class="value">${totalValue}</span>
            </div>
            <div class="detail-row">
              <span>Total Assets:</span>
              <span>${assets.length}</span>
            </div>
            <div class="detail-row">
              <span>Vehicles:</span>
              <span>${assets.filter(a => a.type === "vehicle").length}</span>
            </div>
            <div class="detail-row">
              <span>Properties:</span>
              <span>${assets.filter(a => a.type === "property").length}</span>
            </div>
          </div>

          ${assets
            .map(
              asset => `
            <div class="asset">
              <div class="asset-header">
                <div>
                  <h3>${asset.name}</h3>
                  <span class="asset-type ${
                    asset.type
                  }">${asset.type.toUpperCase()}</span>
                </div>
                <div class="value">${asset.value}</div>
              </div>
              <div class="details">
                <div class="detail-row">
                  <span>Description:</span>
                  <span>${asset.summary}</span>
                </div>
                <div class="detail-row">
                  <span>Added:</span>
                  <span>${asset.createdAt.toLocaleDateString()}</span>
                </div>
                <div class="detail-row">
                  <span>Estimated Value:</span>
                  <span>${asset.value}</span>
                </div>
              </div>
            </div>
          `
            )
            .join("")}

          <div class="footer">
            <p>This report was generated by AssetLens - Professional Asset Valuation Platform</p>
            <p>For the most up-to-date valuations, please visit our platform.</p>
          </div>
        </body>
      </html>
    `;

      reportWindow.document.write(reportHTML);
      reportWindow.document.close();

      // Auto-print after a short delay
      setTimeout(() => {
        reportWindow.print();
      }, 1000);
    } catch (error) {
      console.error("Error generating PDF report:", error);
      alert("Unable to generate PDF report. Please try again.");
    }
  };

  const handleShareReport = () => {
    if (navigator.share) {
      navigator.share({
        title: "My AssetLens Portfolio Report",
        text: `My total asset portfolio is valued at ${totalValue} across ${assets.length} assets.`,
        url: window.location.href,
      });
    } else {
      // Fallback: copy to clipboard
      navigator.clipboard
        .writeText(
          `My AssetLens Portfolio: ${totalValue} across ${assets.length} assets`
        )
        .then(() => {
          alert("Portfolio summary copied to clipboard!");
        });
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center space-x-2">
          <i className="fas fa-file-alt text-primary"></i>
          <span>Portfolio Summary</span>
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-6">
        <div className="grid grid-cols-2 gap-4">
          <div className="text-center p-4 bg-primary/10 rounded-xl border border-primary/20 hover:bg-primary/15 transition-colors">
            <div className="w-10 h-10 bg-primary/20 rounded-full flex items-center justify-center mx-auto mb-2">
              <i className="fas fa-dollar-sign text-primary text-sm"></i>
            </div>
            <div className="text-2xl font-bold text-primary mb-1">
              {totalValue}
            </div>
            <div className="text-sm text-muted-foreground">Total Value</div>
          </div>
          <div className="text-center p-4 bg-secondary/10 rounded-xl border border-secondary/20 hover:bg-secondary/15 transition-colors">
            <div className="w-10 h-10 bg-secondary/20 rounded-full flex items-center justify-center mx-auto mb-2">
              <i className="fas fa-chart-bar text-secondary text-sm"></i>
            </div>
            <div className="text-2xl font-bold text-secondary mb-1">
              {assets.length}
            </div>
            <div className="text-sm text-muted-foreground">
              Asset{assets.length !== 1 ? "s" : ""}
            </div>
          </div>
        </div>

        <div className="text-center">
          <p className="text-sm text-muted-foreground">
            Complete portfolio overview with detailed asset valuations
          </p>
        </div>

        <div className="flex space-x-3">
          <Button onClick={handleDownloadPDF} className="flex-1">
            <i className="fas fa-download mr-2"></i>
            Download PDF Report
          </Button>
          <Button
            variant="outline"
            onClick={handleShareReport}
            className="flex-1"
          >
            <i className="fas fa-share-alt mr-2"></i>
            Share Summary
          </Button>
        </div>

        <div className="text-xs text-muted-foreground text-center pt-2 border-t border-border">
          <p>
            <i className="fas fa-info-circle mr-1"></i>
            Report includes current market valuations and asset details as of{" "}
            {new Date().toLocaleDateString()}
          </p>
        </div>
      </CardContent>
    </Card>
  );
}
